baseURL = "/"
languageCode = "en-us"
title = "BabyLogger"
themesDir = "themes"
theme = "hugo-book"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "What is the BabyLogger?"
    url = "/What is the BabyLogger?/"
    weight = 2

[[menu.main]]
    name = "Getting started"
    url = "/getting started/"
    weight = 3

[[menu.main]]
    name = "Automatic Data Processing"
    url = "/Automatic Data Processing/"
    weight = 4


[[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 5

[[menu.main]]
    name = "Contact"
    url = "/Contact/"
    weight = 6

[params]
  google_analytics_id=""
 
  homepage_image = '/images/render.png'

  ## You can enable to add anchor links to header elements
   enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Babycloud documentation."
    meta_og_title = "BabyLogger Documentation"
    meta_og_type = "website"
   
  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
